SonarSource/sonar-scanner-java-library

sonar-runner-impl/src/main/java/org/sonar/runner/impl/BatchLauncher.java

SONARUNNER-132 Add support for offline mode

---

api/src/main/java/org/sonarsource/scanner/api/internal/OkHttpClientFactory.java
api/src/test/java/org/sonarsource/scanner/api/internal/OkHttpClientFactoryTest.java

SUPPORT-10616 SCANNERAPI-182 change read timeout to be configurable

---

its/it-tests/src/test/java/com/sonar/scanner/api/it/SSLTest.java

Forgot the ITs in the previous PR, this one is intended to fix them.

SCANNERAPI-185 - Fix ITs

---

.cirrus.yml

Move to SonarQube team GCP project

---

pom.xml

Bump junit to 4.13.1

---

its/it-tests/pom.xml
its/it-tests/src/test/java/com/sonar/scanner/api/it/ProxyTest.java
its/it-tests/src/test/java/com/sonar/scanner/api/it/SSLTest.java
its/it-tests/src/test/java/com/sonar/scanner/api/it/ScannerApiTestSuite.java

Upgrade Orchestrator to 3.33.0.2677

---

its/it-tests/pom.xml

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-api/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:

Update IT orchestrator to v3.34.0.2692

---

.github/workflows/release.yml

The workflow file is invalid: https://github.com/SonarSource/sonar-scanner-api/actions/runs/795226394

Rename release job

---

api/pom.xml
batch-interface/pom.xml
batch/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
pom.xml

Preparing for patch release 2.16.2

Prepare for patch release

---

.cirrus.yml

Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team

BUILD-1828 Fix the notifications of the sonar-scanner-api qa tasks

---

.cirrus.star
.cirrus.yml

Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team

BUILD-2279 Migrate CirrusCI to AWS

---

.github/workflows/release.yml

Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-api/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:

fix(BUILD-2387): release github action

---

.github/workflows/release.yml

Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team

fix(BUILD-2387): release workflow

---

.cirrus.yml
its/it-tests/src/test/java/com/sonar/scanner/api/it/SSLTest.java

We have an issue when running our cron job related to a jre environment that cannot run our newest SQ. Therefore, we should upgrade to JAVA17 our QA environment

[NO-JIRA] Set a new JAVA17 env for QA tasks

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml

[SCANJLIB-240](https://sonarsource.atlassian.net/browse/SCANJLIB-240)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last …

SCANJLIB-240 Add Jira integration

---

its/it-tests/pom.xml

[SCANJLIB-243](https://sonarsource.atlassian.net/browse/SCANJLIB-243)
[SCANJLIB-243]: https://sonarsource.atlassian.net/browse/SCANJLIB-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-243 Update Orchestrator to 5.1.0.2254

---

lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/http/OkHttpClientFactory.java
lib/src/test/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapperTest.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/http/OkHttpClientFactoryTest.java

[SCANJLIB-236](https://sonarsource.atlassian.net/browse/SCANJLIB-236)
[SCANJLIB-236]: https://sonarsource.atlassian.net/browse/SCANJLIB-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-236 Rework mapping of JVM SSL properties

---

lib/src/main/java/org/sonarsource/scanner/lib/internal/http/ScannerHttpClient.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/http/ScannerHttpClientTest.java

[SCANJLIB-245](https://sonarsource.atlassian.net/browse/SCANJLIB-245)
[SCANJLIB-245]: https://sonarsource.atlassian.net/browse/SCANJLIB-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-245 Add support for redirects

---

batch-interface/pom.xml
batch/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
lib/pom.xml
pom.xml

[SCANJLIB-253](https://sonarsource.atlassian.net/browse/SCANJLIB-253)
[SCANJLIB-253]: https://sonarsource.atlassian.net/browse/SCANJLIB-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-253 Prepare next dev iteration

---

.github/workflows/release.yml

[SCANJLIB-254](https://sonarsource.atlassian.net/browse/SCANJLIB-254)
[SCANJLIB-254]: https://sonarsource.atlassian.net/browse/SCANJLIB-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-254 Change slack channel for release notification

---

NOTICE.txt
README.md

[SCANJLIB-255](https://sonarsource.atlassian.net/browse/SCANJLIB-255)
[SCANJLIB-255]: https://sonarsource.atlassian.net/browse/SCANJLIB-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-255 Update license in text files

---

batch-interface/pom.xml
batch/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
lib/pom.xml
pom.xml

[REL-3519](https://sonarsource.atlassian.net/browse/REL-3519)
[REL-3519]: https://sonarsource.atlassian.net/browse/REL-3519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

REL-3519 Prepare next dev iteration

---

batch-interface/pom.xml
batch/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
lib/pom.xml
pom.xml

[REL-3540](https://sonarsource.atlassian.net/browse/REL-3540)
[REL-3540]: https://sonarsource.atlassian.net/browse/REL-3540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

REL-3540 Prepare next dev iteration

---

.github/workflows/PullRequestClosed.yml

[SCANJLIB-264](https://sonarsource.atlassian.net/browse/SCANJLIB-264)
This will enable the automation to close issues that it created, to keep things more cleaned up.
Manually created issues will not be affected.
[SCANJLIB-264]: https://sonarsource.atlassian.net/browse/SCANJLIB-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-264 Autoclose issues created by Jira integration

---

lib/pom.xml
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/forked/ScannerEngineLauncher.java

[SCANJLIB-265](https://sonarsource.atlassian.net/browse/SCANJLIB-265)
[SCANJLIB-265]: https://sonarsource.atlassian.net/browse/SCANJLIB-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-265 Restore compatibility with SLF4J 1.x for Maven < 4.x

---

lib/src/main/java/org/sonarsource/scanner/lib/EnvironmentConfig.java
lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineFacade.java
lib/src/main/java/org/sonarsource/scanner/lib/ScannerProperties.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/OfficialSonarQubeCloudInstance.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpoint.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpointResolver.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/SonarQubeServer.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/package-info.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/AbstractScannerEngineFacade.java
lib/src/test/java/org/sonarsource/scanner/lib/EnvironmentConfigTest.java
lib/src/test/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapperTest.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/endpoint/OfficialSonarQubeCloudInstanceTest.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpointResolverTest.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/endpoint/SonarQubeServerTest.java

[SCANJLIB-263](https://sonarsource.atlassian.net/browse/SCANJLIB-263)
[SCANJLIB-263]: https://sonarsource.atlassian.net/browse/SCANJLIB-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-263 Add support for SonarQube Cloud regions

---

lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/OfficialSonarQubeCloudInstance.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpointResolver.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/endpoint/OfficialSonarQubeCloudInstanceTest.java

[SCANJLIB-263](https://sonarsource.atlassian.net/browse/SCANJLIB-263)
Another feedback I forgot from @alban-auzeill 
[SCANJLIB-263]: https://sonarsource.atlassian.net/browse/SCANJLIB-263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-263 Don't let people use the region value 'global'

---

batch-interface/pom.xml
batch/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
lib/pom.xml
pom.xml

[REL-3614](https://sonarsource.atlassian.net/browse/REL-3614)

REL-3614 Prepare next dev iteration

---

batch-interface/pom.xml
batch/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
lib/pom.xml
lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineFacade.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/OfficialSonarQubeCloudInstance.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpoint.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpointResolver.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/SonarQubeServer.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/AbstractScannerEngineFacade.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/forked/NewScannerEngineFacade.java
lib/src/test/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapperTest.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/facade/simulation/SimulationScannerEngineFacadeTest.java
pom.xml

[SCANJLIB-266](https://sonarsource.atlassian.net/browse/SCANJLIB-266)
[SCANJLIB-266]: https://sonarsource.atlassian.net/browse/SCANJLIB-266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-266 Log the SonarQube Cloud Region

---

batch-interface/pom.xml
batch/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
lib/pom.xml
pom.xml

[REL-3633](https://sonarsource.atlassian.net/browse/REL-3633)

REL-3633 Prepare next dev iteration

---

lib/src/test/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpointResolverTest.java

[SCANJLIB-267](https://sonarsource.atlassian.net/browse/SCANJLIB-267)
Feedback from @martin-strecker-sonarsource 
[SCANJLIB-267]: https://sonarsource.atlassian.net/browse/SCANJLIB-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-267 Add missing test cases for the US region

---

.github/workflows/releasability.yml

[SCANJLIB-274](https://sonarsource.atlassian.net/browse/SCANJLIB-274)
[SCANJLIB-274]: https://sonarsource.atlassian.net/browse/SCANJLIB-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-274 Fix releasability check

---

lib/src/main/java/org/sonarsource/scanner/lib/ScannerProperties.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/cache/CachedFile.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/AbstractScannerEngineFacade.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/forked/JavaRunnerFactory.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/forked/NewScannerEngineFacade.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/forked/ScannerEngineLauncher.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/forked/ScannerEngineLauncherFactory.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/inprocess/IsolatedLauncherFactory.java
lib/src/main/java/org/sonarsource/scanner/lib/internal/facade/simulation/SimulationScannerEngineFacade.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/cache/FileCacheTest.java
lib/src/test/java/org/sonarsource/scanner/lib/internal/facade/forked/ScannerEngineLauncherFactoryTest.java

[SCANJLIB-276](https://sonarsource.atlassian.net/browse/SCANJLIB-276)
[SCANJLIB-276]: https://sonarsource.atlassian.net/browse/SCANJLIB-276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-276 Allow to use a local Scanner Engine

---

batch-interface/pom.xml
batch/pom.xml
download-cache/pom.xml
its/it-simple-scanner/pom.xml
its/it-tests/pom.xml
its/pom.xml
lib/pom.xml
pom.xml

[REL-3854](https://sonarsource.atlassian.net/browse/REL-3854)
[REL-3854]: https://sonarsource.atlassian.net/browse/REL-3854?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

REL-3854 Prepare next dev iteration

---

batch/pom.xml

[SCANJLIB-282](https://sonarsource.atlassian.net/browse/SCANJLIB-282)
[SCANJLIB-282]: https://sonarsource.atlassian.net/browse/SCANJLIB-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANJLIB-282 Upgrade SonarQube dependency
